<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>My chat con sockets</title>';
echo '<link rel="stylesheet" href="https://bootswatch.com/4/spacelab/bootstrap.min.css">';
echo '<script src="socket.io.js"></script>';
echo '<script src="main.js"></script>';
echo '</head>';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-primary">';
echo '<a href="/" class="navbar-brand">CHAT CON NODE JS</a>';
echo '</nav>';
echo '<br>';
echo '<center><div class="card text-white bg-success mb-3" style="max-width: 20rem;">';
echo '<div class="card-header">CHAT</div>';
echo '<div class="card-body">';
echo '<center><div id="messages"></div></center>';
echo '</div>';
echo '</div>';
echo '</center>';
echo '<br>';
echo '<center><form onsubmit="return addMessage(this)">';
echo '<div class="col-md-5">';
echo '<div class="form-group">';
echo '<input type="text" id="username" placeholder="Tu Nombre" >';
echo '</div>';
echo '<div class="form-group">';
echo '<input type="text" id="texto" placeholder="Mensaje...">';
echo '</div>';
echo '<button type="submit" class="btn btn-primary" value="Enviar!">';
echo 'Enviar';
echo '</button>';
echo '<br>';
echo '</div>';
echo '</form>';
echo '</center>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<nav class="navbar navbar-dark bg-dark" id="footer">';
echo '<a href="/" class="navbar-brand"></a>';
echo '<br>';
echo '<br>';
echo '</nav>';
echo '</body>';
echo '</html>';
?>